# Activity 6: Eigenvectors and Eigenvalues of Symmetric Matrices

In [ ]:
import numpy as np
from numpy import random as RA
from numpy import linalg as LA

## Approximating eigenvalues and eigenvectors
### Exercise 1: Some random utility functions
Below, we'll embark on some approaches to computing eigenvectors and eigenvalues of symmetric matrices numerically.
Before we do, we'll need a few random generation utility functions.
`np.random.rand(n)` (for convenience, imported as `RA.rand(n)`) yields a vector of size `n` with entries given by a normally distributed pseudorandom selection on the interval $[0,1)$.
Later, we'll need some means of selecting (lots of) random unit vectors.
There's one complication to this: our unit vectors will need both positive and negative entries!
Below is a function to supply a vector with entries normally distributed on $[-1,1)$ rather than $[0,1)$.

**(a)** Use this to write a function which supplies a random unit vector.

In [ ]:
def random_vector(n):
    v=RA.random(n)
    v=2*v-1
    return v
def random_unit_vector():
    #YOUR CODE HERE
    return

In [ ]:
#testing
v=random_unit_vector(100)
v_pos_table=np.array([vi>0 for vi in v])
v_neg_table=np.array([vi<0 for vi in v])
print(LA.norm(v),np.any(v_pos_table) and np.any(v_neg_table),sep=",")
#Desired output: 1.0,True
#You might get something like 0.9999999999999999,True -- that's also fine

Later, it will also be useful to have a function to supply a random $n\times n$ symmetric matrix. `RA.rand(n,n)` gives a random non-symmetric matrix with entries again distributed normally on $[0,1)$. 

**(b)** Write a function below which uses `RA.rand` to give a symmetric matrix with entries distributed normally on $[-a,a)$ where $a$ is an optional argument set by default to 1.

In [ ]:
def random_symmetric_matrix():
    #YOUR CODE HERE
    return

In [ ]:
#testing
#M=RA.rand(100,100)
M=random_symmetric_matrix(100,100)
M_vec=np.ndarray.flatten(M)  #convert to a list
M_high_pos_table=[m>50 for m in M_vec]
M_low_pos_table=[m<50 and m>0 for m in M_vec]
M_low_neg_table=[m>-50 and m<0 for m in M_vec]
M_high_neg_table=[m<-50 for m in M_vec]
M_symmetry=np.array_equal(M,np.transpose(M))
np.any(M_high_pos_table) and np.any(M_low_pos_table) and np.any(M_high_neg_table) and np.any(M_low_neg_table) and M_symmetry

## Exercise 1
We'll also later need to select random unit vectors of length $n$ from the orthogonal complement to a list of unit vectors $u_1,u_2,\dots,u_n$ where $n$ can be. We'll achieve this by letting one of our arguments be a list (set by default to empty).
**Exercise:** Write such a function! You can indeed assume the supplied list of vectors consists of unit vectors (which should simplify the formulas somewhat).
<details>
    <summary> <b> Hint: </b> (click to expand) </summary>
    
-    All we need is for the output vector `v` to be a unit vector and to be orthogonal to `u_1,...,u_n`. You've written a function like that before!

</details>

In [ ]:
def random_unit_vector_orthonormal_to():
    #YOUR CODE HERE
    return
        

In [ ]:
#testing:
v1=np.array([1,0,0],"float64")
v2=np.array([0,np.sqrt(2)/2,-np.sqrt(2)/2],"float64")
v3=random_unit_vector_orthonormal_to(3,[v1,v2])
v3
#Desired output:
#array([0.        , 0.70710678, 0.70710678])
#or
#array([ 0.        , -0.70710678, -0.70710678])

In [ ]:
#testing pt 2:
u1=random_unit_vector_orthonormal_to(4)
u2=random_unit_vector_orthonormal_to(4,[u1])
u3=random_unit_vector_orthonormal_to(4,[u1,u2])
u4=random_unit_vector_orthonormal_to(4,[u1,u2,u3])
U=np.transpose([u1,u2,u3,u4])
np.dot(np.transpose(U),U),np.dot(U,np.transpose(U))
#what should we expect the output to be?

## Eigenvalues of Symmetric matrices
The key observation making it feasible to write a relatively elementary function finding eigenvalues of an arbitrary symmetric matrix with real entries is the following theorem in Olver-Shakiban (pp.432):
**Theorem 8.32:** Let $A=A^T$ be a real symmetric $n\times n$ matrix. Then,
- (a) All eigenvalues of $A$ are real.
- (b) Eivenvectors corresponding to distinct eigenvalues are orthogonal
- (c) There is an orthonormal basis of $\mathbb{R}^n$ consisting of $n$ eigenvectors of $A$.


## Eigenvalues of Symmetric matrices
The key observation making it feasible to write a relatively elementary function finding eigenvalues of an arbitrary symmetric matrix with real entries is the *Spectral Theorem*, recalled in Olver-Shakiban as theorem 8.38:

**Theorem:** Let $A$ be a real, symmetric matrix. Then, there exists an orthogonal matrix $Q$ such that $A=Q\Lambda Q^{-1}=Q\Lambda Q^T$ where $\Lambda$ is a real diagonal matrix. The diagonal entries of $\Lambda$ are the eigenvalues of $A$ and the corresponding columns of $Q$ are the corresponding [orthonormal] eigenvectors.

Suppose $A$ is $n\times n$ with eigenvalues $\lambda_1\geq \lambda_2 \geq \dots \geq \lambda_n$ and consider the quadratic form $q(\vec x)=\vec x ^T A \vec x$. Letting $\vec y=Q^T \vec x$, we have that $$q(\vec x) = \vec y ^T \Lambda \vec y= \sum_{i=1}^n \lambda_i y_i^2.$$ Restricting to unit vectors $\vec y$, it is clear that $q$ achieves a maximum of $\lambda_1$ when $\vec y =(1, 0, \dots, 0)$ and minimum of $\lambda_n$ when $\vec y =(0,\dots, 0,1)$. Noting that $\vec y = Q^T\vec x$ is a unit vector if and only if $\vec x $ is a unit vector yields the following:

**Theorem:** $q(\vec x)= \vec x^T A\vec x$ has a maximum among unit vectors $\vec x$ of $\lambda_1$, achieved when $\vec x$ is a $\lambda_1$-eigenvector and a minimum of $\lambda_n$, achieved when $\vec x$ is a $\lambda_n$-eigenvector.

### Exercise 2: Dominant eigenvalues
Below, write a function which takes as input a real symmetric matrix `A` and an integer `num_iters` and gives as output a tuple `(l_1,v_1,l_n,v_n)` where `l_1` is [an approximation of] the greatest eigenvalue of `A`, `l_n` is the least eigenvector of `A` and `v_1` and `v_n` are respectively `l_1`- and `l_n`-eigenvalues.
Do this by plugging in a `random_unit_vector` to the quadratic form $q$ as above `num_iters` times and recording the maximal and minimal values.
<details>
    <summary> <b> Hints: </b> (Click here to open) </summary>
    
- When finding minima and maxima, remember our trick of initializing the maximum as `-np.inf` and the minimum as `np.inf`!
- Use a for loop quantified over `range(num_iters)` to repeat the process of choosing a random vector `num_iters` times. Note that there's no rule dictating that you must use your indexing variable!
    </details>

In [ ]:
def dom_eigens():
    #YOUR CODE HERE
    return
        

In [ ]:
M=np.array([[33.35333333, 33.32333333, 33.32333333],
       [33.32333333, 35.83833333, 30.83833333],
       [33.32333333, 30.83833333, 35.83833333]])
dom_eigens(M)
#desired output: something approximating
#(99.99957171960315,
# array([-0.57870294, -0.57757057, -0.57577352]),
# 0.03093244890258169,
# array([ 0.81481521, -0.40680568, -0.41301975]))

## Exercise 3: Symmetric Eigensolver
Now, we'll combine several of the functions we've written today to write a function which approximately computes all eigenvalues and eigenvectors of symmetric matrices. 
Suppose $A$ is $n\times n$ with eigenvalues $\lambda_1\geq \lambda_2\geq \dots \geq \lambda_n$.
Then, as we've now learned, the maximum value of $q(\vec x)=\vec x^T A \vec x$ among unit vectors $\vec x$ is $\lambda_1$, achieved at a $\lambda_1$-eigenvector $\vec v_1$.
Moreover, we've also seen that $\vec v_1$ fits into an orthonormal basis of $A$-eigenvectors $\vec v_2,\dots,\vec v_n$ (where each $\vec v_i$ is a $\lambda_i$-eigenvector.
Thus, among unit vectors orthogonal to $\vec v_1$, $q$ has a maximum of $\lambda_2$ achieved at a $\lambda_2$-eigenvector $\vec v_2$.
And more generally, for $k\leq n$, among unit vectors orthogonal to $\vec v_1,\dots \vec v_{k-1}$, $q$ is has a maximum of $\lambda_k$ achieved at $\vec v_k$.

**Exercise: (a)** Use this series of observations along with `random_unit_vector_orthonormal_to` to write a function which takes as input a real symmetric matrix `A` and produces a tuple `(lambdas,Q)` where `lambdas` is a vector of `A`'s eigenvalues (ordered from most to least, repeating as necessary) and `Q` is an orthogonal matrix with each `i`th column a `lambdas[i]`-eigenvector.
Your function should once again take a parameter `num_iters` which governs how many repetitions through the process of plugging in random vectors to go through for each time through the process.

<details>
<summary>
<b>
Hint:    
</b>
(Click here to open)
</summary>
You can choose whether to find two eigenvalues at a time by taking simultaneous maxima and minima (as above) or just one at a time. If you choose to work with two at a time, be sure you find some way to correctly order the eigenvalues.
    
</details>


In [ ]:
def symmetric_eigensolver():
    #YOUR CODE HERE
    return


In [ ]:
#testing
M=np.array([[33.35333333, 33.32333333, 33.32333333],
       [33.32333333, 35.83833333, 30.83833333],
       [33.32333333, 30.83833333, 35.83833333]])
symmetric_eigensolver(M,10**5)
#desired output:
#something approximating
#(array([1.e+02, 5.e+00, 3.e-02]),
# array([[-5.77350269e-01,  0.00000000e+00, -8.16496581e-01],
#        [-5.77350269e-01, -7.07106781e-01,  4.08248290e-01],
#        [-5.77350269e-01,  7.07106781e-01,  4.08248290e-01]]))

In practice, this is a wildly inefficient and inaccurate method of finding spectral data for an arbitrary symmetric matrix. An introduction to more practical methods can be found in Olver-Shakiban, section 9.5 for those interested.
To demonstrate the poor accuracy of our method, let's put it to the test.

**(b):** Write a function `reconstruct` which takes as input a matrix `A` and a parameter `num_iters` and reconstructs `A` by the spectral factorization $A=Q\Lambda Q^T$ (`np.diag` is a helpful built-in function which converts between vectors and diagonal matrices (and vice-versa)). Then, for various values of `n`, run `reconstruct` on a random symmetric matrix with entries in $[-10,10)$ and check the accuracy of your results by finding the maximum amount by which an entry of your reconstructed `A` differs from the original. Write a few words about your observations. At what `n` does the discrepancy hit 1 for you? How about 5? 10?

*Hint:* Remember that while the base python built-in `abs` works for `ndarray`s, `max` does not. Use `np.max` instead.

In [ ]:
def reconstruct():
    #YOUR CODE HERE
    return

In [1]:
#YOUR CODE HERE

(Empty markdown cell for your observations)
